.DEFAULT_GOAL := help
SHELL=/bin/bash -e
.PHONY: blueprint-all
blueprint-all: blueprint-Dockerfile-all blueprint-bake
.PHONY: blueprint-bake
blueprint-bake:
	@docker run --rm -v "$$(pwd)/:/repo:ro" dinutac/jinja2docker:latest /repo/docker-bake.hcl.j2 > docker-bake.hcl
	@sed -i "1i\# DO NOT EDIT THIS FILE : It's generated from ./docker-bake.hcl.j2" docker-bake.hcl
	@echo "docker-bake.hcl => Generated"
